# Generated by Django 5.1.1 on 2024-10-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/manual_images/'),
        ),
    ]
