# Generated by Django 5.1.1 on 2024-10-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0004_question_quiz_choice_question_quiz'),
        ('web_portal', '0004_user'),
    ]

    operations = [
    ]
