# Generated by Django 5.1.1 on 2024-10-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0005_merge_20241005_0210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
