# Generated by Django 5.1.1 on 2024-10-05 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0007_merge_0005_merge_20241005_0214_0006_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
